name: Static Checks

on:
  pull_request:
    paths:
      - "app/**"
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest
    environment: dev
    concurrency:
      group: ${{ github.workflow }}-pr-staticcheck-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - id: checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        working-directory: app

      - id: setup
        uses: ./.github/actions/setup-composite
        working-directory: app

      - id: run-tsc
        run: yarn tsc
        working-directory: app

      - id: run-lint
        run: yarn lint
        working-directory: app

      - id: run-prettier
        run: yarn prettier:check
        working-directory: app

      - id: run-test
        run: yarn test
        working-directory: app
